// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Entity struct {
	ID            string          `json:"id"`
	Kind          *Kind           `json:"kind"`
	Name          *TimeBasedValue `json:"name"`
	Created       *string         `json:"created,omitempty"`
	Terminated    *string         `json:"terminated,omitempty"`
	Relationships []*Relationship `json:"relationships"`
}

type EntityInput struct {
	ID            *string              `json:"id,omitempty"`
	Kind          *KindInput           `json:"kind,omitempty"`
	Name          *TimeBasedValueInput `json:"name,omitempty"`
	Created       *string              `json:"created,omitempty"`
	Terminated    *string              `json:"terminated,omitempty"`
	Relationships *RelationshipInput   `json:"relationships,omitempty"`
}

type Kind struct {
	Major string `json:"major"`
	Minor string `json:"minor"`
}

type KindInput struct {
	Major *string `json:"major,omitempty"`
	Minor *string `json:"minor,omitempty"`
}

type Query struct {
}

type Relationship struct {
	ID              *string   `json:"id,omitempty"`
	RelatedEntityID string    `json:"relatedEntityId"`
	Name            string    `json:"name"`
	StartTime       string    `json:"startTime"`
	EndTime         *string   `json:"endTime,omitempty"`
	Direction       string    `json:"direction"`
	Entities        []*Entity `json:"entities"`
}

type RelationshipInput struct {
	ID              *string `json:"id,omitempty"`
	RelatedEntityID *string `json:"relatedEntityId,omitempty"`
	Name            *string `json:"name,omitempty"`
	StartTime       *string `json:"startTime,omitempty"`
	EndTime         *string `json:"endTime,omitempty"`
	Direction       *string `json:"direction,omitempty"`
}

type TimeBasedValue struct {
	StartTime string  `json:"startTime"`
	EndTime   *string `json:"endTime,omitempty"`
	Value     any     `json:"value"`
}

type TimeBasedValueInput struct {
	StartTime *string `json:"startTime,omitempty"`
	EndTime   *string `json:"endTime,omitempty"`
	Value     *string `json:"value,omitempty"`
}
